services:

  backend:
    build: 
      context: ./backend
    ports:
      - "4000:4000"
    command: ["npm" ,"run", "start"]
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    command: ["npm", "run" ,"dev"]